url: https://chvsp.github.io
baseurl: /

# Site settings
title: 
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Praveen Chavali
  pic: 1
  position: He's been dabbling in improv comedy for about 5 years, doing some stuff here and there—Mumbai, Munich, Berlin. Once tried to teach improv to a flock of pigeons. They weren't impressed, but he's still trying to find his comedic wings.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Yash Bhotica
  pic: 2
  position: A former lawyer who traded his gavel for giggles after moving to Bangalore. Unsurprisingly, his favorite improv game is "Objections Only." Makes you wonder if old habits die hard or just get funnier.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Akhil Harikumar
  pic: 3
  position: An improviser, dancer and filmmaker for whom improv isn't just an art; it's the ultimate life hack. When stuck in an improv scene? He dances his way out, turning awkward pauses into comedic gold. 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty